### ISSUE TITLE
error with userconfig.h

### ISSUE THREAD

**Issue by dovrose** [polclota/esp32lywsd03mmc#3]
Hello,

I have a prblem to complice, I have the following error:
`include/userconfig.h:1:74: fatal error: myprivatedate.h: No such file or directory`

can you help me with it? 

Dov

**Comment by polclota** [comment]
You have to create a file named myprivatedate.h in include directory with your wifi and Mqtt server data 

#define WIFINAME "xxx"
#define PASSWORD "xxx"
#define MQTT_SERVER "xxx"
#define  MQTT_USER "xxx"
#define  MQTT_PW "xxx"

or override the constatants in userconfig.h.
