### ISSUE TITLE
Thanks for the project

### ISSUE THREAD

**Issue by 1technophile** [polclota/esp32lywsd03mmc#4]
I would like to thank you for this implementation, the LYWSD03MMC integration has been requested many times into [OpenMQTTGateway](https://github.com/1technophile/OpenMQTTGateway)
Your code helped me understand and find a working sequence for the integration.
I will push the modification soon, OpenMQTTGateway is licensed under GPL V3 for info, so let me know if it is an issue for you.

If you have any question do not hesitate.

**Comment by polclota** [comment]
As I quote in my main source file, my code is based on [[karolkalinski's](https://github.com/karolkalinski/esp32-snippets/tree/master/Mijia-LYWSD03MMC-Client)] one. I'll be pleased if anyone uses it for whatever profitable endeavour.
